name: currency_converter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #dependency injection
  get_it: ^9.2.0

  #local storage
  shared_preferences: ^2.5.4
  drift: ^2.30.1
  drift_flutter: ^0.2.8


  #state management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  #navigation
  go_router: ^17.0.1

  #env
  flutter_dotenv: ^6.0.0

  #path
  path: ^1.9.1
  path_provider: ^2.1.5

  #network
  dio: ^5.9.0

  #logger
  pretty_dio_logger: ^1.4.0

  #image
  cached_network_image: ^3.4.1

  #formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.6
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - .env